wip
Signed-off-by: Jan Kowalleck <jan.kowalleck@gmail.com>

diff --git a/.github/workflows/test_2.x_java.yml b/.github/workflows/test_2.x_java.yml
--- a/.github/workflows/test_2.x_java.yml
+++ b/.github/workflows/test_2.x_java.yml
@@ -50,4 +50,8 @@ jobs:
     - name: test with Maven
       env:
         SCHEMA_VERSION: ${{ matrix.schema_version }}
-      run: mvn clean test -P "schema-v${SCHEMA_VERSION}-tests"
+      run: |
+        mvn help:all-profiles | grep -q "Profile Id: schema-v${SCHEMA_VERSION}-tests" \
+          || { echo "::error::No Maven profile 'schema-v${SCHEMA_VERSION}-tests' in tools/pom.xml"; \
+               exit 1; }
+        mvn clean test -P "schema-v${SCHEMA_VERSION}-tests"
